term_mappings = term_mapping_extract = {
    "Fruit": "Fruit",
    "Fruits": "Fruit",
    "fruit": "Fruit",
    "fruits": "Fruit",
    "fruiting perianths": "Fruit",
    "Fruiting perianths": "Fruit",
    "Inflorescences": "Inflorescence",
    "inflorescences": "Inflorescence",
    "partial inflorescences": "Partial inflorescence",
    "Partial inflorescences": "Partial inflorescence",
    "Partial inflorescence": "Partial inflorescence",
    "pistillate inflorescences": "Pistillate inflorescence",
    "Pistillate inflorescences": "Pistillate inflorescence",
    "staminate inflorescences": "Staminate inflorescence",
    "Staminate inflorescence": "Staminate inflorescence",
    "Staminate inflorescences": "Staminate inflorescence",
    "Pistillate inflorescence": "Pistillate inflorescence",
    "Pistillate partial inflorescences": "Pistillate partial inflorescence",
    "Leaf": "Leaf",
    "leaf": "Leaf",
    "middle pinnae": "Pinna",
    "proximalmost pinnae": "Pinna",
    "Proximalmost pinnae": "Pinna",
    "Distalmost pinnae": "Pinna",
    "distalmost pinnae": "Pinna",
    "Distalmost few": "Pinna",
    "distalmost few": "Pinna",
    "Pinnae": "Pinna",
    "pinnae": "Pinna",
    "distal pair": "Pinna",
    "Distal pair": "Pinna",
    "Peduncles": "Peduncle",
    "peduncles": "Peduncle",
    "Petioles": "Petioles and rachises",
    "petioles": "Petioles and rachises",
    "Petiole": "Petioles and rachises",
    "pistillate rachillae": "Pistillate rachilla",
    "Pistillate rachillae": "Pistillate rachilla",
    "Pistillate rachilla": "Pistillate rachilla",
    "pistillate rachilla": "Pistillate rachilla",
    "Rachillae": "Rachilla",
    "rachillae": "Rachilla",
    "Rachilla": "Rachilla",
    "rachilla": "Rachilla",
    "Rachilla-subtending bracts": "Rachilla-subtending bract",
    "rachilla-": "Rachilla-subtending bract",
    "Rachis": "Petioles and rachises",
    "rachis": "Petioles and rachises",
    "rachises": "Petioles and rachises",
    "Rachises": "Petioles and rachises",
    "Rachis apices": "Petioles and rachises",
    "Raphe": "Raphe",
    "raphe": "Raphe",
    "Seeds": "Seed",
    "seeds": "Seed",
    "Staminate flowers": "Staminate flower",
    "staminate flowers": "Staminate flower",
    "Staminate rachillae": "Staminate rachilla",
    "staminate rachillae": "Staminate rachilla",
    "Staminate rachilla": "Staminate rachilla",
    "staminate rachilla": "Staminate rachilla",
    "Staminate sepals": "Staminate sepal",
    "staminate sepals": "Staminate sepal",
    "Stamens": "Stamen",
    "stamens": "Stamen",
    "stems": "Stem",
    "Stems": "Stem",
    "Stem": "Stem",
    "Prophylls": "Prophyll",
    "prophylls": "Prophyll",
    "Ocreas": "Ocrea",
    "ocreas": "Ocrea",
    "Embryos": "Embryo",
    "embryos": "Embryo",
    "Endosperm": "Endosperm",
    "endosperm": "Endosperm",
    "Flagella": "Flagellum",
    "flagella": "Flagellum",
    "Filaments": "Filament",
    "filaments": "Filament",
    "flowers": "Flower",
    "Neuter flowers": "Pistillate rachilla",
    "pistillate calyces": "Pistillate calyx",
    "Pistillate calyces": "Pistillate calyx",
    "Pistillate dyads": "Pistillate dyads"
}