term_mappings = term_mapping_gen = {
    "Fruit": "Fruit",
    "Fruits": "Fruit",
    "fruit": "Fruit",
    "fruits": "Fruit",
    "fruiting perianths": "Fruit",
    "Fruiting perianths": "Fruit",
    "Inflorescences": "Inflorescence",
    "inflorescences": "Inflorescence",
    "partial inflorescences": "Partial inflorescence",
    "Partial inflorescences": "Partial inflorescence",
    "Partial inflorescence": "Partial inflorescence",
    "pistillate inflorescences": "Pistillate structures",
    "Pistillate inflorescences": "Pistillate structures",
    "staminate inflorescences": "Staminate structures",
    "Staminate inflorescence": "Staminate structures",
    "Staminate inflorescences": "Staminate structures",
    "Pistillate inflorescence": "Pistillate structures",
    "Pistillate partial inflorescences": "Pistillate structures",
    "Leaf": "Leaf",
    "leaf": "Leaf",
    "middle pinnae": "Pinna",
    "proximalmost pinnae": "Pinna",
    "Proximalmost pinnae": "Pinna",
    "Distalmost pinnae": "Pinna",
    "distalmost pinnae": "Pinna",
    "Distalmost few": "Pinna",
    "distalmost few": "Pinna",
    "Pinnae": "Pinna",
    "pinnae": "Pinna",
    "distal pair": "Pinna",
    "Distal pair": "Pinna",
    "Peduncles": "Peduncle",
    "peduncles": "Peduncle",
    "Petioles": "Petioles and rachises",
    "petioles": "Petioles and rachises",
    "Petiole": "Petioles and rachises",
    "pistillate rachillae": "Pistillate structures",
    "Pistillate rachillae": "Pistillate structures",
    "Pistillate rachilla": "Pistillate structures",
    "pistillate rachilla": "Pistillate structures",
    "Rachillae": "Rachilla",
    "rachillae": "Rachilla",
    "Rachilla": "Rachilla",
    "rachilla": "Rachilla",
    "Rachilla-subtending bracts": "Rachilla",
    "rachilla-": "Rachilla",
    "Rachis": "Petioles and rachises",
    "rachis": "Petioles and rachises",
    "rachises": "Petioles and rachises",
    "Rachises": "Petioles and rachises",
    "Rachis apices": "Petioles and rachises",
    "Raphe": "Seed",
    "raphe": "Seed",
    "Seeds": "Seed",
    "seeds": "Seed",
    "Seed": "Seed",
    "seed": "Seed",
    "Staminate flowers": "Staminate structures",
    "staminate flowers": "Staminate structures",
    "Staminate rachillae": "Staminate structures",
    "staminate rachillae": "Staminate structures",
    "Staminate rachilla": "Staminate structures",
    "staminate rachilla": "Staminate structures",
    "Staminate sepals": "Staminate structures",
    "staminate sepals": "Staminate structures",
    "Stamens": "Staminate structures",
    "stamens": "Staminate structures",
    "stems": "Stem",
    "Stems": "Stem",
    "Stem": "Stem",
    "Prophylls": "Prophyll",
    "prophylls": "Prophyll",
    "Ocreas": "Ocrea",
    "ocreas": "Ocrea",
    "Embryos": "Seed",
    "embryos": "Seed",
    "Endosperm": "Seed",
    "endosperm": "Seed",
    "Flagella": "Flagellum",
    "flagella": "Flagellum",
    "Filaments": "Staminate structures",
    "filaments": "Staminate structures",
    "flowers": "Flower",
    "Neuter flowers": "Pistillate structures",
    "pistillate calyces": "Pistillate structures",
    "Pistillate calyces": "Pistillate structures",
    "Pistillate dyads": "Pistillate structures"
}